### ISSUE TITLE
Isn't working on mask border

### ISSUE THREAD

**Issue by bragan202** [lewishowles/sketch-replace-colour#1]
Almost perfect plugin (thanks!). It's not working in one instance that I've found...on the border of a mask. In my case, I have a folder. Inside that folder is an image masked by a circle. The circle's border will not change when I use the plugin. Possible fix?

**Comment by lewishowles** [comment]
Thanks for the kind words!

Do you mind sending me your Sketch document? I've just given this a try and it seemed to work OK for me.
