### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jbernbach** [lewishowles/sketch-replace-colour#13]
First, this plug-in is awesome... but the bug is that the plug-in replaces the new HEX with white (instead of the new color you inserted into the text field). Almost 100% of the time. Once it replaced my color with bright green.

I downloaded the latest version of the plug-in 2.0.3 and I am using Sketch 4.1
I rebooted my machine as well.

Thanks. Best

**Comment by lewishowles** [comment]
This looks to be related to #12. For me it always does the right colour, but the Hex value Sketch shows in the box is incorrect, which could be causing the weirdness. Not sure why it's doing that yet.

**Comment by jbernbach** [comment]
I didn't read 12 until you sent it to me. Thanks
Wish you luck. This is one of the best plug-ins. It's so useful when designing

**Comment by lewishowles** [comment]
This should now be fixed in 2.0.4
