### ISSUE TITLE
Plug In Seems To Be Broken

### ISSUE THREAD

**Issue by TurboDingus** [lewishowles/sketch-replace-colour#16]
Selecting a layer and running the script has no effect. The dialog shows no layer being selected.

**Comment by lewishowles** [comment]
Seems to be OK to me - what version of Sketch are you running?

**Comment by TurboDingus** [comment]
Running on 42

**Comment by lewishowles** [comment]
Could you check the version of the plugin you have as I can't get it to fail

**Comment by TurboDingus** [comment]
Working ok now after reinstall. thanks
