### ISSUE TITLE
could't work

### ISSUE THREAD

**Issue by olafchou** [lewishowles/sketch-replace-colour#19]
<img width="416" alt="2017-04-12 15 33 06" src="https://cloud.githubusercontent.com/assets/19890798/24946399/5a02c478-1f95-11e7-8bf1-d18a22917148.png">

when you choose  All   ,it failed to change color

**Comment by lewishowles** [comment]
Hi,

The colour you entered in the screenshot isn't valid.

**Comment by olafchou** [comment]
haha ，thank you
