### ISSUE TITLE
Update identifier in manifest.json

### ISSUE THREAD

**Issue by mludowise** [lewishowles/sketch-replace-colour#21]
This plugin cannot automatically update in [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) because its identifier conflicts with another plugin [nmwoods1/Sketch---Find-all-instances-of-symbol](https://github.com/nmwoods1/Sketch---Find-all-instances-of-symbol).

See http://developer.sketchapp.com/introduction/plugin-bundles/ for more info.

**Comment by mludowise** [comment]
Thank you!

**Comment by MrrRoman** [comment]
Plugin doesn't work with sketch 52,2 :(
Work with some object correct (text, simple object), with some doesn't open.
