### ISSUE TITLE
ReplaceColour Dialog Box not appearing in Sketch v52.6

### ISSUE THREAD

**Issue by hsdajr** [lewishowles/sketch-replace-colour#27]
I hadn't used Sketch since about September of last year so I believe I was running v51.3 at that time, and this plugin worked fine (only plugin I use).

Needed to use Sketch and it asked to update, so I did. Whether I use the key command or the menu item to select ReplaceColour, the menu changes to indicate the selection, but the dialog box doesn't come up.

One other point, the last time I used Sketch may have been before I upgraded to Mojave.
Help!

**Comment by lewishowles** [comment]
Hi there,

This functionality is built into Sketch now - I forget which menu it’s in but you can search in the help menu for replace color and it should come up.

**Comment by hsdajr** [comment]
Lewis,

I apologize, I did not realize this.
Thanks for the quick response!


Andy
hsdajr@mac.com

We are here to make a dent in the universe.
Otherwise, why even be here? - Steve Jobs: Apple, Inc.

There is nothing noble in being superior to some other person.
True nobility comes from being superior to your previous self.
Hindu Proverb

(Sent from an Apple-Empowered device.)

**Comment by lewishowles** [comment]
No problem. Theirs doesn’t quite have all the same features but keeping plugins up to date was more frustrating than it should be!
