### ISSUE TITLE
Support Version 56.3

### ISSUE THREAD

**Issue by annarobertson** [lewishowles/sketch-replace-colour#28]
Is this plugin going to be updated at all? It's the only colour replace plugin available!!

**Comment by annarobertson** [comment]
Should have read the other issues. Saw that Sketch built this in. Thanks!

**Comment by lewishowles** [comment]
Ha, yeah. I had to abandon it because they kept changing the plugin API and never really documented it so it was never worth trying to figure it out with nothing to go on. Not sure if the situation is better now or not.

But luckily as you say they built it in themselves.

**Comment by annarobertson** [comment]
Makes sense! Yes glad they built in a find and replace. Thanks for your reply! :)

**Comment by lewishowles** [comment]
No problem! I doesn’t quite have all the features of my plugin but it’s fine for most people.

To be fair I’ve been trying to set things up recently so that I’m using layer styles or swatches more so if I change those it affects everywhere I use that colour

**Comment by annarobertson** [comment]
Yes we use a shared library and palette which makes it much easier. Of course changing the main library symbol file is where I would use this plugin the most!
