### ISSUE TITLE
Does not seem to apply color changes in Sketch 3.6.1

### ISSUE THREAD

**Issue by jydesign** [lewishowles/sketch-replace-colour#4]
Hello, I seem to be having issues in Sketch 3.6.1:
- choose a layer
- open Plugin from /Plugins and it offers me the dialog, fill out new color and tried various options (was trying to replace fill on multiple layers)
- click OK
- no changes are made to elements

Any suggestions? thank you

**Comment by lewishowles** [comment]
Hi there,

It seems to be OK for me in most cases - the one requirement is that layers are inside Artboards - is that the case for you?

**Comment by jydesign** [comment]
Ah, thank you for that clarification - I tested quickly on a new doc on the infinite canvas. Works fine on artboards, thanks!
