### ISSUE TITLE
Doesn't respect selection

### ISSUE THREAD

**Issue by rorysmyth** [lewishowles/sketch-replace-colour#6]
Look like a useful plugin, but it doesn't respect groups or selected layers. It just applies the replacement to the entire document.

**Comment by lewishowles** [comment]
That was the intention with this plugin at the moment as that's how I use it - if a client changes their colour palette for example.

If I get time at some point I'll look into whether it would be possible to use the selection. This will probably be a non-default option to not break any current expectations.
