### ISSUE TITLE
39.1 support?

### ISSUE THREAD

**Issue by alanontheweb** [lewishowles/sketch-replace-colour#7]
Does this plugin still work with the latest version of Sketch?

**Comment by lewishowles** [comment]
Yes. It currently only works for layers inside artboards.

**Comment by alanontheweb** [comment]
Ah, thank you. I was hoping to modify this to make it swap hues instead of entire hexademicals. Is such a thing possible (if using the HSLA fields)?

**Comment by lewishowles** [comment]
It probably would be but not in the current scope of the project. What you could probably do is set the opacity of the layer (if possible in context), and use simple hex colours, meaning updating the hex would keep the opacity.

**Comment by alanontheweb** [comment]
No problem. I forked the code and made a version that replaces the hues - https://github.com/alanontheweb/sketch-replace-hue/issues

I initially went with your method above, but using a tool like Avocode, it wasn't possible for developers to extract the proper HSLA values with it. Using a color picker, they could get the hex, but that would still leave us with hex values that are not easily swappable in the same way hues are.

**Comment by lewishowles** [comment]
Cool, looks good. At the moment it's quite frustrating as they keep changing how plugins work and the documentation isn't as complete as it could be so I find myself not using my plugins as much as I'd hoped (and not updating them as much!). Ideally this and many other features could be added, preferably with a custom UI!

**Comment by alanontheweb** [comment]
Yeahh, I struggled with that myself. Sketch Plugin documentation is pretty barebones. And definitely feel free to integrate it if you'd like, and make any improvements to the codebase.

I think Invision's Craft does a good job at color replacement as well, but it doesn't account for borders/text like yours does. And it doesn't do hues either.
