### ISSUE TITLE
使用 SketchI18N master后，此插件不可用

### ISSUE THREAD

**Issue by hanuse** [lewishowles/sketch-replace-colour#8]
使用 SketchI18N master本地化后，此颜色替换插件不可用

**Comment by lewishowles** [comment]
If @cute can provide any pointers about how to allow his plugin to translate mine I'd be happy to build it in.

**Comment by lewishowles** [comment]
@cute

**Comment by cute** [comment]
@lewishowles  pull request https://github.com/lewishowles/sketch-replace-colour/issues/9

i18n plugin will replace NSComboBox stringValue property, if will use it, must be saved as other property first.
